name: Update Database

on:
  push:
    branches: ["main"]
    paths:
      - 'data/**'

jobs:
  update_data:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: write
    env:
      ENTSOE_API_KEY: ${{ secrets.ENTSOE_API_KEY }}
      LOG_LEVEL: WARNING
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install Dependencies
        run: pipenv install

      - name: Update ENTSOE Data
        run: pipenv run python update_database.py update_entsoe

      - name: Update SMARD Data
        run: pipenv run python update_database.py update_smard

      - name: Update EPEXSPOT Data
        run: pipenv run python update_database.py update_epexspot
        
      - name: Update OpenMeteo Offshore Windfarms Data
        run: pipenv run python update_database.py update_openmeteo_windfarms_offshore

      - name: Update OpenMeteo Onshore Windfarms Data
        run: pipenv run python update_database.py update_openmeteo_windfarms_onshore

      - name: Update OpenMeteo Solarfarms Data
        run: pipenv run python update_database.py update_openmeteo_solarfarms

      - name: Update OpenMeteo Cities Data
        run: pipenv run python update_database.py update_openmeteo_cities

      - name: Commit Updated Data
        run: |
          git config --global user.name 'Collector'
          git config --global user.email 'noreply@nedora.digital'
          git add database/
          git commit -m "Add data for today"
          git pull -r
          git push
