name: Update Forecasts

on:
  workflow_run:
    workflows:
      - Update Database
    types:
      - completed
  push:
    branches: ["main"]
    paths:
      - 'database/**'

jobs:
  update_forecasts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ENTSOE_API_KEY: ${{ secrets.ENTSOE_API_KEY }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install Dependencies
        run: pipenv install

      - name: Update Forecasts
        run: pipenv run python update_forecasts.py

      - name: Switch to gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Remove existing files in deploy/data
        run: |
          rm -rf deploy/data
          mkdir -p deploy/data

      - name: Commit removal of old files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -u deploy/data
          git commit -m "Remove old forecast files" || echo "No files to remove"

      - name: Copy updated files from main branch
        run: git checkout main -- deploy/data

      - name: Commit and push changes
        run: |
          git add deploy/data
          git commit -m "Update forecasts data"
          git push origin gh-pages
